# 4.0 Introduction to Numpy

In [2]:
import numpy as np

In [3]:
array_spell = np.arange(1_000_000)

In [4]:
my_list = list(range(1_000_000))

In [5]:
%timeit array_mult_2_spell = array_spell * 2

199 μs ± 1.43 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
%timeit list_mult_2_spell = [x*2 for x in my_list]

28.2 ms ± 163 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 4.1 The NumPy ndarray: A Multidimensional Array Object

In [9]:
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])

In [10]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [12]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [13]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [17]:
data.shape

(2, 3)

In [19]:
data.dtype

dtype('float64')

## 4.1.1 Creating Arrays

In [21]:
data1 = [6,7.5,8,0,1]

In [43]:
uni_dimensional_array = np.array(data1)

In [23]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [42]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [45]:
multi_dimensional_array1 = np.array(data2)

In [47]:
multi_dimensional_array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
print(f'N = {multi_dimensional_array1.ndim}')

N = 2


### 4.1.1.1 Array initializations

In [57]:
arr1 = np.zeros(15)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
arr2 = np.zeros((2,6))
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [62]:
arr3 = np.arange(15)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
arr4 = np.ones_like(arr2)
arr4

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### 4.1.1.2 Array Data Transformation

In [68]:
arr1 = np.array(["1.0","2.0","42"], dtype=np.bytes_)
arr1

array([b'1.0', b'2.0', b'42'], dtype='|S3')

In [75]:
arr1.astype('float64')

array([ 1.,  2., 42.])

### 4.1.1.3 Arithmetic with NumPy Arrays
So this section is basically explained by abstracting classic deterministic thinking about `for lopps` as more concise but complex algebraic ways. Hence the vectorization of lists.

### 4.1.1.4 Indexing and Slicing

In [77]:
arr = np.arange(10)
arr[5]

np.int64(5)

In [79]:
arr[5:8]

array([5, 6, 7])

In [81]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [88]:
# Indexing with slicing

# Syntathic Sugar
# np.tile(row, (number_of_rows_repeats, number_of_column_repeats))
# array = np.tile(arange(10), (2,1))

array = np.array([np.arange(10),np.arange(10),np.arange(10)])
array


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [89]:
# Axis 0 slicing
array[:2]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [91]:
# Axis 0 and Axis 1 slicing
array[:2,:5]

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [92]:
# Axis 1 slicing
array[:,:5]

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [95]:
# Boolean Indexing

names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [99]:
data = np.array([
[4,7], # Bob
[0,2],
[-5,6],
[0,0], # Bob
[1,2],
[-12,-4],
[3,4]
])

data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [100]:
# Boolean Negation
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])